name: GroupPlugin
main: plugin\plugin
version: 1.0.0
api: [1.14.0]
load: POSTWORLD
author: 骸の王
commands:
    groupjoin:
        description: GroupJoin
        usage:"Usage: /groupjoin"
    groupcreate:
        description: GroupCreate
        usage:"Usage: /groupcreate"
